import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans"
import "./globals.css";
import QueryProviderWrapper from "./QueryProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" data-theme="dark">
      <body
        className={`${GeistSans.className} antialiased bg-white text-gray-950 dark:text-gray-100 dark:bg-gray-950 transition-colors`}
      >
        <QueryProviderWrapper>
          {children}
        </QueryProviderWrapper>
      </body>
    </html>
  );
}
