name: Run unit tests

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "REACT_APP_LOCAL_STORAGE=BUDGET_MASTER" > .env

      - name: Run unit tests
        run: pnpm test
